# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d5a07cc6e999e49d7d8c4857fd438bca1fd656f57ce6f28e8e2f64b78d2abb01cb0212a28c646ab0e5923e45390d5a73031f848d5780f9426012f0036e395e1

test:
  secret_key_base: 5b74841b7a0e8bba8f2335b37e153f78ea2a2c1a7646b775f5b5c9cc16a108de5a407d0c105cce7a8a404d87177888064c234a3648d8693f1095e926cf90574d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
